#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - OpenLDAP & Register with AI Manager
#  - RobotShop Demo App
#  - Demo Service Account 
#  - AWX (Open Source Ansible Tower) with preloaded Playbooks
#  - Disables ASM Service match rule 
#  - Train Models
#    - Create Training Definitions (TG, LAD, CR, SI. Turn off RSA) 
#    - Create Training Data (LAD, SNOW) 
#    - Train Models (TG, LAD, CR, SI) 
#  - Topology
#    - Create K8s Observer
#    - Create ASM merge rules
#    - Load ASM merge Topology
#    - Create AI Manager Application
#  - Creates valid certificate for Ingress (Slack) 
#  - External Routes (Flink, Topology, ...)
#  - Disables ASM Service match rule 
#  - Create Policy Creation for Stories and Runbooks 
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  #vars_files: {{ config_file }}

  tasks:
  - name: 🚀 MAIN INSTALLATION LOOP - Install Module
    debug: 
      msg: 
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "                                                                                                                                                   "
      - "       CloudPak for Watson AIOps - INSTALLATION - AI Manager Demo Content Only                                                           "
      - "                                                                                                                                                   "
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"


  - name: 🛠️  Config File Path
    set_fact: config_file_path="./configs/cp4waiops-roks-aimanager-demo-content-35.yaml"


  - name: 🛠️  Show Global Config
    debug:
      var: config_file_path

  - name: 🛠️  Ansible check config file exists
    stat:
      path: "{{config_file_path}}"
    register: p
  - debug:
      msg: "  ✅ Config File exists..."
      #verbosity: 2
    when: p.stat.exists
  - fail: msg="The specified config file {{config_file_path}} does not exist"
    when: p.stat.exists == False
      
  - name: 🛠️  Import Config File
    include_vars:
      file: "{{config_file_path}}"
      name: config_file

  - name: 🟣  Show Config File
    debug:
      var: all_config
      #verbosity: 2


  - name: 🛠️  Set Global Config
    set_fact: global_config={{ all_config.global_config | default([]) }}
  - name: 🟣  Show Global Config
    debug:
      var: global_config
      #verbosity: 2


  - name: 🛠️  Set Openshift Config
    set_fact: openshift_cluster={{ all_config.openshift | default([]) }}
  - name: 🟣  Show Openshift Config
    debug:
      var: openshift_cluster
      #verbosity: 2


  # Loop over all Clusters
  - name: ♻️  Deploy Cloud Pak for Watson AIOps Assets - Loop over Clusters
    include_role:
      name: cp4waiops-install
    loop: "{{ all_config.cp4waiops | default([]) }}"
    loop_control:
      loop_var: current_cp4waiops_cluster

